# Generated by Django 5.1.3 on 2024-11-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новая', 'New'), ('Принято', 'Accept'), ('Выполнено', 'Done')], default='Новая', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
